package golang

var goParserTemplate = `// Code generated by u3k_lexer. DO NOT EDIT.
package {{.Package}}

import (
	"github.com/pkg/errors"
	"io"
	lr "{{.LexerRuntime}}"
	pr "{{.ParserRuntime}}"
)


type nodeType struct{
	name string
	t    pr.Type
}

func (n *nodeType) String() string{
	return n.name
}

func (n *nodeType) Type() pr.Type{
	return n.t
}

func newNodeType(name string,t pr.Type) pr.NodeType{
	return &nodeType{
		name: name,
		t : t,
	}
}

var(
	{{ range $idx,$symbol := .Idx2Symbol }}
	TokenType_{{$symbol.Name}} runtime.TokenType = newTokenType("{{$symbol.Name}}",{{$symbol.SymbolType}})
	{{ end }}
)

type parser struct{
	lexer lr.Lexer
	curTerminal *pr.Node
	eof   error
}

func (p *parser) nextTerminal(){
	token,p.eof:=p.lexer.NextToken()
	if p.eof!=nil{
		curTerminal==nil	
		return 
	}
	curTerminal = 
}

func (p *parser) Parse() (*Node, error){
	
}

{{range $idx,$rightIdx:=range .Idx2RightIdxs}}
func (p *parser) {{.MethodName $idx}}(){
	if p.curToken
}
{{end }}
`
